version: '3.8'

services:
  api_gateway:
    image: isdockero/api_gateway_notesphere:latest
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.api_gateway == true
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongo:
    image: isdockero/mongo_with_prom:latest
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb_exporter:
    image: percona/mongodb_exporter:latest
    environment:
      MONGODB_URI: "mongodb://monitor:monitorPassword@mongo:27017/admin"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  prometheus:
    image: prom/prometheus:latest
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.prometeus == true

  grafana:
    image: grafana/grafana:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.grafana == true

volumes:
  minio_data:
  mongo_data:
  grafana_data:
    driver: local

networks:
  app-network:
    external: true

configs:
  prometheus_config:
    file: ./../prometheus.yml