global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: speech-to-text-notesphere-manager
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - tasks.speech-to-text-notesphere-manager
        refresh_interval: 10s
        type: A
        port: 8080
  - job_name: speech-to-text-notesphere-processor
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - tasks.speech-to-text-notesphere-processor
        refresh_interval: 10s
        type: A
        port: 8080
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: [ 'minio:9000' ]