spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: stt_request
          uri: http://speech-to-text-notesphere-manager:8080
          predicates:
            - Path=/ai/speech-to-text/request
          filters:
            - "RewritePath=/ai/speech-to-text/request, /request"

        - id: stt_result
          uri: http://speech-to-text-notesphere-manager:8080
          predicates:
            - Path=/ai/speech-to-text/result/{request_id}
          filters:
            - "RewritePath=/ai/speech-to-text/result/(.*), /result/$1"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
